### PR TITLE
Changes to make the API work with the Ember app from the book

### PR DESCRIPTION
**Pull request by lackac**
The commit messages speak for themselves.

### CODE REVIEW

**Comment by kernicPanel** [comment]
@balinterdi :
This PR really needs to be merged to your heroku app.
I spend too much time trying to install this, instead of learning ember…
(I really hate ruby version issues…)

If you merge this, your rarwe demo app will be (almost) instantly working. It would be great.
Thanks @lackac for these commits.

**Comment by balinterdi** [comment]
@kernicPanel There are several moving pieces but I might eventually end up merging this. In the meantime, please connect to `http://api.rockandrollwithemberjs.com` which is compatible with the application in the RARWE book. You should set the `apiHost` variable to the above host to make it work.

**Comment by kernicPanel** [comment]
Oh great, thank you, @balinterdi

**Comment by kernicPanel** [comment]
Hello @balinterdi 
Can you close this pr please ? I'd like to clean my https://github.com/pulls/mentioned view :)

**Comment by balinterdi** [comment]
@kernicPanel Sure! Closing as this is no longer relevant.

**Comment by kernicPanel** [comment]
Thanks @balinterdi :pray:

**Pull request closed without merging**
